# Generated by Django 5.2.6 on 2025-09-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['slug'], name='ecommerce_p_slug_b8decd_idx'), models.Index(fields=['-id'], name='ecommerce_p_id_33071d_idx')],
            },
        ),
    ]
